
public class LostDashboardFrame extends javax.swing.JFrame {

   
    public LostDashboardFrame() {
        initComponents();
        this.setSize(410, 700);
        this.setLocationRelativeTo(null);
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblWelcomeText = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lblMenuIcon = new javax.swing.JLabel();
        lblNotificationBell = new javax.swing.JLabel();
        lblLostAndFound = new javax.swing.JLabel();
        lblWelcomeText1 = new javax.swing.JLabel();
        lblSubtitleText = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        btnTabLost = new javax.swing.JButton();
        btnTabFound = new javax.swing.JButton();
        lblCategoriesTitle = new javax.swing.JLabel();
        lblCatLibrary = new javax.swing.JLabel();
        lblCatITLabs = new javax.swing.JLabel();
        lblCatSportsHall = new javax.swing.JLabel();
        lblCatCafeteria = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lblNavHome = new javax.swing.JLabel();
        lblNavMessages = new javax.swing.JLabel();
        lblNavProfile = new javax.swing.JLabel();
        btnFloatingAdd = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        lblWelcomeText.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblWelcomeText.setForeground(new java.awt.Color(153, 153, 153));
        lblWelcomeText.setText("Welcome, Farah!");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Lost & Found App");

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel13.setText("X");
        jLabel13.setPreferredSize(new java.awt.Dimension(150, 150));

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 51, 51));
        jLabel16.setText("Location: Library");

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 102));
        jLabel15.setText("Keys");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(103, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addGap(29, 29, 29))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel16)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblMenuIcon.setText("☰");

        lblNotificationBell.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        lblNotificationBell.setText("🔔");

        lblLostAndFound.setBackground(new java.awt.Color(153, 153, 153));
        lblLostAndFound.setIcon(new javax.swing.ImageIcon(getClass().getResource("/WhatsApp Image 2026-05-23 at 9.16.47 AM.jpeg"))); // NOI18N

        lblWelcomeText1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblWelcomeText1.setForeground(new java.awt.Color(153, 153, 153));
        lblWelcomeText1.setText("Welcome, Farah!");

        lblSubtitleText.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblSubtitleText.setForeground(new java.awt.Color(0, 0, 153));
        lblSubtitleText.setText("What have you lost today?");

        jLabel6.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        jLabel6.setText("🔎");

        txtSearch.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtSearch.setForeground(new java.awt.Color(153, 153, 153));
        txtSearch.setText("Search for items...");
        txtSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSearchMouseClicked(evt);
            }
        });

        btnTabLost.setBackground(new java.awt.Color(0, 153, 0));
        btnTabLost.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnTabLost.setForeground(new java.awt.Color(0, 0, 102));
        btnTabLost.setText("Lost");
        btnTabLost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTabLostActionPerformed(evt);
            }
        });

        btnTabFound.setBackground(new java.awt.Color(255, 255, 255));
        btnTabFound.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnTabFound.setForeground(new java.awt.Color(0, 0, 102));
        btnTabFound.setText("Found");
        btnTabFound.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTabFoundActionPerformed(evt);
            }
        });

        lblCategoriesTitle.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblCategoriesTitle.setForeground(new java.awt.Color(0, 0, 102));
        lblCategoriesTitle.setText("Categories");

        lblCatLibrary.setBackground(new java.awt.Color(204, 204, 204));
        lblCatLibrary.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblCatLibrary.setForeground(new java.awt.Color(0, 0, 153));
        lblCatLibrary.setText("Library");
        lblCatLibrary.setOpaque(true);

        lblCatITLabs.setBackground(new java.awt.Color(204, 204, 204));
        lblCatITLabs.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblCatITLabs.setForeground(new java.awt.Color(0, 0, 153));
        lblCatITLabs.setText("IT Labs");
        lblCatITLabs.setOpaque(true);

        lblCatSportsHall.setBackground(new java.awt.Color(204, 204, 204));
        lblCatSportsHall.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblCatSportsHall.setForeground(new java.awt.Color(0, 0, 153));
        lblCatSportsHall.setText("Sports Hall");
        lblCatSportsHall.setOpaque(true);

        lblCatCafeteria.setBackground(new java.awt.Color(204, 204, 204));
        lblCatCafeteria.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblCatCafeteria.setForeground(new java.awt.Color(0, 0, 153));
        lblCatCafeteria.setText("Cafeteria");
        lblCatCafeteria.setOpaque(true);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 102));
        jLabel12.setText("Latest Reports:");

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel14.setText("X");
        jLabel14.setPreferredSize(new java.awt.Dimension(150, 150));

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(51, 51, 51));
        jLabel17.setText("Location: Sports Hall");

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 102));
        jLabel18.setText("ID Card");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel17)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addGap(80, 80, 80))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel17)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));

        lblNavHome.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblNavHome.setForeground(new java.awt.Color(0, 0, 102));
        lblNavHome.setText("Home");
        lblNavHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNavHomeMouseClicked(evt);
            }
        });

        lblNavMessages.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblNavMessages.setForeground(new java.awt.Color(0, 0, 102));
        lblNavMessages.setText("Messages");
        lblNavMessages.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNavMessagesMouseClicked(evt);
            }
        });

        lblNavProfile.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblNavProfile.setForeground(new java.awt.Color(0, 0, 102));
        lblNavProfile.setText("Profile");
        lblNavProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNavProfileMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNavHome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(lblNavMessages)
                .addGap(51, 51, 51)
                .addComponent(lblNavProfile)
                .addGap(31, 31, 31))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lblNavHome)
                .addComponent(lblNavMessages)
                .addComponent(lblNavProfile))
        );

        btnFloatingAdd.setBackground(new java.awt.Color(0, 153, 0));
        btnFloatingAdd.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 48)); // NOI18N
        btnFloatingAdd.setForeground(new java.awt.Color(51, 51, 51));
        btnFloatingAdd.setText("+");
        btnFloatingAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFloatingAddMouseClicked(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 102));
        jButton1.setText("Details");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblMenuIcon)
                                .addGap(132, 132, 132)
                                .addComponent(lblLostAndFound)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblNotificationBell))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblSubtitleText)
                                    .addComponent(lblWelcomeText1))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(btnTabLost)
                                .addGap(62, 62, 62)
                                .addComponent(btnTabFound))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblCategoriesTitle)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblCatLibrary)
                                .addGap(18, 18, 18)
                                .addComponent(lblCatITLabs)
                                .addGap(18, 18, 18)
                                .addComponent(lblCatSportsHall)
                                .addGap(18, 18, 18)
                                .addComponent(lblCatCafeteria))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel12))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnFloatingAdd)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblNotificationBell)
                        .addComponent(lblMenuIcon))
                    .addComponent(lblLostAndFound))
                .addGap(1, 1, 1)
                .addComponent(lblWelcomeText1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSubtitleText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTabLost)
                    .addComponent(btnTabFound))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCategoriesTitle)
                    .addComponent(lblCatLibrary)
                    .addComponent(lblCatITLabs)
                    .addComponent(lblCatSportsHall)
                    .addComponent(lblCatCafeteria))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnFloatingAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(245, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSearchMouseClicked
        String searchQuery = txtSearch.getText();
        if (!searchQuery.trim().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Searching for: " + searchQuery);
        }
    }//GEN-LAST:event_txtSearchMouseClicked

    private void btnTabLostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTabLostActionPerformed
        javax.swing.JOptionPane.showMessageDialog(this, "Filtering by: Lost Items");
    }//GEN-LAST:event_btnTabLostActionPerformed

    private void btnTabFoundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTabFoundActionPerformed
      MainDashboardFrame foundPage = new MainDashboardFrame();
foundPage.setVisible(true);
this.dispose();
        javax.swing.JOptionPane.showMessageDialog(this, "Filtering by: Found Items at Security");
    }//GEN-LAST:event_btnTabFoundActionPerformed

    private void lblNavMessagesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNavMessagesMouseClicked
      MessagesFrame messages = new MessagesFrame();
messages.setVisible(true);
this.dispose();
        javax.swing.JOptionPane.showMessageDialog(this, "No new messages in your inbox.");
    }//GEN-LAST:event_lblNavMessagesMouseClicked

    private void lblNavProfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNavProfileMouseClicked
        MyProfileFrame profile = new MyProfileFrame();
profile.setVisible(true);
this.dispose();
        javax.swing.JOptionPane.showMessageDialog(this, "Opening Farah's Profile...");

    }//GEN-LAST:event_lblNavProfileMouseClicked

    private void lblNavHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNavHomeMouseClicked

        LostDashboardFrame home = new LostDashboardFrame();
home.setVisible(true);
this.dispose();txtSearch.setText("");
        javax.swing.JOptionPane.showMessageDialog(this, "Lost Items dashboard refreshed!", "Home", javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_lblNavHomeMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ItemDetailsFrame details = new ItemDetailsFrame();
        details.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnFloatingAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFloatingAddMouseClicked
      PostItemFrame postItem = new PostItemFrame();
postItem.setVisible(true);
this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFloatingAddMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LostDashboardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LostDashboardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LostDashboardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LostDashboardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LostDashboardFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFloatingAdd;
    private javax.swing.JButton btnTabFound;
    private javax.swing.JButton btnTabLost;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblCatCafeteria;
    private javax.swing.JLabel lblCatITLabs;
    private javax.swing.JLabel lblCatLibrary;
    private javax.swing.JLabel lblCatSportsHall;
    private javax.swing.JLabel lblCategoriesTitle;
    private javax.swing.JLabel lblLostAndFound;
    private javax.swing.JLabel lblMenuIcon;
    private javax.swing.JLabel lblNavHome;
    private javax.swing.JLabel lblNavMessages;
    private javax.swing.JLabel lblNavProfile;
    private javax.swing.JLabel lblNotificationBell;
    private javax.swing.JLabel lblSubtitleText;
    private javax.swing.JLabel lblWelcomeText;
    private javax.swing.JLabel lblWelcomeText1;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
