
public class PostItemFrame extends javax.swing.JFrame {

    
    public PostItemFrame() {
        initComponents();
        this.setSize(410, 700);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        lblLostAndFound = new javax.swing.JLabel();
        lblBack = new javax.swing.JLabel();
        btnTabLost = new javax.swing.JButton();
        btnTabFound = new javax.swing.JButton();
        lblName = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblCategory = new javax.swing.JLabel();
        lblDetails = new javax.swing.JLabel();
        lblLocation = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtLocation = new javax.swing.JTextField();
        txtCategory = new javax.swing.JTextField();
        txtDetails = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lblNavHome = new javax.swing.JLabel();
        lblNavMessages = new javax.swing.JLabel();
        lblNavProfile = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Lost & Found App");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setText("Post New Item");

        lblLostAndFound.setBackground(new java.awt.Color(153, 153, 153));
        lblLostAndFound.setIcon(new javax.swing.ImageIcon(getClass().getResource("/WhatsApp Image 2026-05-23 at 9.16.47 AM.jpeg"))); // NOI18N

        lblBack.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblBack.setForeground(new java.awt.Color(0, 0, 153));
        lblBack.setText("<");
        lblBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBackMouseClicked(evt);
            }
        });

        btnTabLost.setBackground(new java.awt.Color(255, 255, 255));
        btnTabLost.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnTabLost.setForeground(new java.awt.Color(0, 0, 102));
        btnTabLost.setText("Lost");
        btnTabLost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTabLostActionPerformed(evt);
            }
        });

        btnTabFound.setBackground(new java.awt.Color(255, 255, 255));
        btnTabFound.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnTabFound.setForeground(new java.awt.Color(0, 0, 102));
        btnTabFound.setText("Found");
        btnTabFound.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTabFoundActionPerformed(evt);
            }
        });

        lblName.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblName.setForeground(new java.awt.Color(0, 0, 102));
        lblName.setText("Item Name:");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 102));

        lblCategory.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblCategory.setForeground(new java.awt.Color(0, 0, 102));
        lblCategory.setText("Category:");

        lblDetails.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblDetails.setForeground(new java.awt.Color(0, 0, 102));
        lblDetails.setText("Description:");

        lblLocation.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblLocation.setForeground(new java.awt.Color(0, 0, 102));
        lblLocation.setText("Location:");

        txtName.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtName.setForeground(new java.awt.Color(153, 153, 153));
        txtName.setText("Enter item name (e.g. University ID)");

        txtLocation.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtLocation.setForeground(new java.awt.Color(153, 153, 153));
        txtLocation.setText("Select where it was lost/found");

        txtCategory.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtCategory.setForeground(new java.awt.Color(153, 153, 153));
        txtCategory.setText("Select category (Electronics, Books, etc.)");

        txtDetails.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtDetails.setForeground(new java.awt.Color(153, 153, 153));
        txtDetails.setText("Add more details (Color, Brand, distinct marks...)");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 102));
        jLabel7.setText("Upload Image:");

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        jLabel14.setFont(new java.awt.Font("Segoe UI Symbol", 0, 48)); // NOI18N
        jLabel14.setText("📷");
        jLabel14.setPreferredSize(new java.awt.Dimension(150, 150));

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(51, 51, 51));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 102));
        jLabel8.setText("Supported formats: JPG, PNG");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel17)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel8))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addGap(0, 32, Short.MAX_VALUE))
        );

        btnSubmit.setBackground(new java.awt.Color(0, 153, 0));
        btnSubmit.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnSubmit.setText("Submit Report");
        btnSubmit.setOpaque(true);
        btnSubmit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSubmitMouseClicked(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 102));
        jLabel9.setText("Your post will be visible after Security Department approval.");

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));

        lblNavHome.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblNavHome.setForeground(new java.awt.Color(0, 0, 102));
        lblNavHome.setText("Home");
        lblNavHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNavHomeMouseClicked(evt);
            }
        });

        lblNavMessages.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblNavMessages.setForeground(new java.awt.Color(0, 0, 102));
        lblNavMessages.setText("Messages");
        lblNavMessages.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNavMessagesMouseClicked(evt);
            }
        });

        lblNavProfile.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblNavProfile.setForeground(new java.awt.Color(0, 0, 102));
        lblNavProfile.setText("Profile");
        lblNavProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNavProfileMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNavHome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(lblNavMessages)
                .addGap(48, 48, 48)
                .addComponent(lblNavProfile)
                .addGap(34, 34, 34))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNavHome, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblNavMessages)
                        .addComponent(lblNavProfile)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(74, 74, 74)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel7)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblDetails)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtDetails))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(2, 2, 2)
                            .addComponent(lblCategory)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtCategory))
                        .addComponent(lblName)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblLocation)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblBack)
                                    .addGap(74, 74, 74)
                                    .addComponent(jLabel2))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(75, 75, 75)
                                    .addComponent(btnTabLost)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnTabFound)))
                            .addGap(26, 26, 26)
                            .addComponent(lblLostAndFound)
                            .addGap(19, 19, 19)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(btnSubmit))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel9))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnTabLost)
                            .addComponent(btnTabFound)))
                    .addComponent(lblLostAndFound)
                    .addComponent(lblBack))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLocation)
                    .addComponent(txtLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCategory))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDetails))
                .addGap(29, 29, 29)
                .addComponent(jLabel7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackMouseClicked
        new MainDashboardFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblBackMouseClicked

    private void btnTabLostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTabLostActionPerformed
        LostDashboardFrame lostPage = new LostDashboardFrame();
lostPage.setVisible(true);
this.dispose();
        javax.swing.JOptionPane.showMessageDialog(this, "Filtering by: Lost Items");
    }//GEN-LAST:event_btnTabLostActionPerformed

    private void btnTabFoundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTabFoundActionPerformed
      MainDashboardFrame foundPage = new MainDashboardFrame();
foundPage.setVisible(true);
this.dispose();
        javax.swing.JOptionPane.showMessageDialog(this, "Filtering by: Found Items at Security");
    }//GEN-LAST:event_btnTabFoundActionPerformed

    private void btnSubmitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSubmitMouseClicked
       javax.swing.JOptionPane.showMessageDialog(this, "Your report has been submitted successfully!");
       LostDashboardFrame dashboard = new LostDashboardFrame();
dashboard.setVisible(true);
this.dispose();
        javax.swing.JOptionPane.showMessageDialog(this, "Connecting to Al-Zaytoonah University Security Department...\nPhone: +962 XXXXXXXX", "Security Contact", javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnSubmitMouseClicked

    private void lblNavHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNavHomeMouseClicked
        new MainDashboardFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblNavHomeMouseClicked

    private void lblNavMessagesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNavMessagesMouseClicked
       MessagesFrame messages = new MessagesFrame();
messages.setVisible(true);
this.dispose();
        javax.swing.JOptionPane.showMessageDialog(this, "No new messages in your inbox.");
    }//GEN-LAST:event_lblNavMessagesMouseClicked

    private void lblNavProfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNavProfileMouseClicked
        MyProfileFrame profile = new MyProfileFrame();
profile.setVisible(true);
this.dispose();
        javax.swing.JOptionPane.showMessageDialog(this, "Opening Farah's Profile...");
    }//GEN-LAST:event_lblNavProfileMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PostItemFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PostItemFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PostItemFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PostItemFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PostItemFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnSubmit;
    private javax.swing.JButton btnTabFound;
    private javax.swing.JButton btnTabLost;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblBack;
    private javax.swing.JLabel lblCategory;
    private javax.swing.JLabel lblDetails;
    private javax.swing.JLabel lblLocation;
    private javax.swing.JLabel lblLostAndFound;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblNavHome;
    private javax.swing.JLabel lblNavMessages;
    private javax.swing.JLabel lblNavProfile;
    private javax.swing.JTextField txtCategory;
    private javax.swing.JTextField txtDetails;
    private javax.swing.JTextField txtLocation;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
