/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author farah
 */
public class RegisterFrame extends javax.swing.JFrame {

    /**
     * Creates new form RegisterFrame
     */
    public RegisterFrame() {
        initComponents();
        
         this.setSize(410, 700);
    this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLostAndFound = new javax.swing.JLabel();
        lblRegister = new javax.swing.JLabel();
        lblCreate = new javax.swing.JLabel();
        txtFullName = new javax.swing.JLabel();
        txtUniversityID = new javax.swing.JLabel();
        txtMajor = new javax.swing.JLabel();
        txtEmail = new javax.swing.JLabel();
        txtPassword = new javax.swing.JLabel();
        btnRegister = new javax.swing.JButton();
        lblHaveAccaunt = new javax.swing.JLabel();
        lblSignin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Lost & Found App");

        lblLostAndFound.setIcon(new javax.swing.ImageIcon(getClass().getResource("/تصميم بدون عنوان (2).png"))); // NOI18N

        lblRegister.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        lblRegister.setForeground(new java.awt.Color(0, 0, 102));
        lblRegister.setText("Register");

        lblCreate.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblCreate.setForeground(new java.awt.Color(0, 0, 153));
        lblCreate.setText("Create your account");

        txtFullName.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtFullName.setForeground(new java.awt.Color(153, 153, 153));
        txtFullName.setText("Full Name");

        txtUniversityID.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtUniversityID.setForeground(new java.awt.Color(153, 153, 153));
        txtUniversityID.setText("University ID");

        txtMajor.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtMajor.setForeground(new java.awt.Color(153, 153, 153));
        txtMajor.setText("Major");

        txtEmail.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(153, 153, 153));
        txtEmail.setText("University Email");

        txtPassword.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(153, 153, 153));
        txtPassword.setText("Password");

        btnRegister.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnRegister.setForeground(new java.awt.Color(0, 0, 102));
        btnRegister.setText("Register");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        lblHaveAccaunt.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblHaveAccaunt.setForeground(new java.awt.Color(0, 0, 153));
        lblHaveAccaunt.setText("Already have an account?");

        lblSignin.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblSignin.setForeground(new java.awt.Color(0, 0, 153));
        lblSignin.setText("Sign in");
        lblSignin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSigninMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFullName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtUniversityID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtMajor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(lblLostAndFound))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(lblCreate))
                            .addComponent(lblRegister)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(btnRegister))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblHaveAccaunt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblSignin)))
                .addGap(0, 66, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLostAndFound)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblRegister)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCreate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFullName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUniversityID, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtMajor, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRegister)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHaveAccaunt)
                    .addComponent(lblSignin))
                .addContainerGap(71, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
          String fullName = txtFullName.getText();
String studentID = txtUniversityID.getText();
String major = txtMajor.getText();
String email = txtEmail.getText();
String password = txtPassword.getText();

if (fullName.trim().isEmpty() || studentID.trim().isEmpty() || major.trim().isEmpty() || email.trim().isEmpty() || password.trim().isEmpty()) {
    javax.swing.JOptionPane.showMessageDialog(this, "Please fill in all fields!", "Validation Error", javax.swing.JOptionPane.ERROR_MESSAGE);
} else {
    javax.swing.JOptionPane.showMessageDialog(this, "Registration Successful!");
    SignInFrame signIn = new SignInFrame();
    signIn.setVisible(true);
    this.dispose();
}


    }//GEN-LAST:event_btnRegisterActionPerformed

    private void lblSigninMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSigninMouseClicked
SignInFrame signIn = new SignInFrame();
signIn.setVisible(true);
this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_lblSigninMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegister;
    private javax.swing.JLabel lblCreate;
    private javax.swing.JLabel lblHaveAccaunt;
    private javax.swing.JLabel lblLostAndFound;
    private javax.swing.JLabel lblRegister;
    private javax.swing.JLabel lblSignin;
    private javax.swing.JLabel txtEmail;
    private javax.swing.JLabel txtFullName;
    private javax.swing.JLabel txtMajor;
    private javax.swing.JLabel txtPassword;
    private javax.swing.JLabel txtUniversityID;
    // End of variables declaration//GEN-END:variables
}
